server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Jinli03
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
ip: localhost